# ============================================================
#  DB Security Lab — CN5134 | Spring 2026
#  Member 1: Project Lead & Docker Integration
# ============================================================

services:

  # ──────────────────────────────────────────────
  # VULNERABILITY 1 — PostgreSQL RCE (CVE-2019-9193)
  # Member 2's work lives here
  # Attack: COPY TO PROGRAM for OS command execution
  # ──────────────────────────────────────────────
  vuln1-db:
    image: postgres:12.0
    container_name: vuln1-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labdb
    volumes:
      - ./vuln1/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./flag.txt:/tmp/flag.txt
    networks:
      - lab-network
    restart: unless-stopped

  vuln1-app:
    build:
      context: ./vuln1
      dockerfile: Dockerfile
    container_name: vuln1-flask
    ports:
      - "5001:5001"
    depends_on:
      - vuln1-db
    networks:
      - lab-network
    restart: on-failure

  # ──────────────────────────────────────────────
  # VULNERABILITY 2 — Blind SQL Injection
  # Member 3's work lives here
  # ──────────────────────────────────────────────
  vuln2-db:
    image: mysql:8.0
    container_name: vuln2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logindb
    volumes:
      - ./vuln2/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lab-network
    restart: unless-stopped

  vuln2-app:
    build:
      context: ./vuln2
      dockerfile: Dockerfile
    container_name: vuln2-flask
    ports:
      - "5002:5002"
    depends_on:
      - vuln2-db
    networks:
      - lab-network
    restart: on-failure

  # ──────────────────────────────────────────────
  # VULNERABILITY 3 — NoSQL Injection (MongoDB)
  # Member 4's work lives here
  # ──────────────────────────────────────────────
  vuln3-db:
    image: mongo:6.0
    container_name: vuln3-mongo
    volumes:
    - ./vuln3/init/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - lab-network
    restart: unless-stopped

  vuln3-app:
    build:
      context: ./vuln3
      dockerfile: Dockerfile
    container_name: vuln3-flask
    ports:
      - "5003:5003"
    depends_on:
      - vuln3-db
    networks:
      - lab-network
    restart: on-failure

networks:
  lab-network:
    driver: bridge
    name: db-security-lab-network